services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://app:password@db:5432/app?serverVersion=15&charset=utf8"
    volumes:
      - ./var:/var/www/html/var
    entrypoint: ["/bin/sh", "-c", "until pg_isready -U app -h db -p 5432; do echo 'Waiting for database...'; sleep 2; done; php bin/console doctrine:database:create --if-not-exists && php bin/console doctrine:schema:update --force && apache2-foreground"]
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
